### ISSUE TITLE
Cannot find blackfriday

### ISSUE THREAD

**Issue by almereyda** [cooper/quiki#92]
When attempting to install quiki with

    go get github.com/cooper/quiki

as of https://quiki.app/get-started, it fails with

```
package github.com/russross/blackfriday/v2: cannot find package "github.com/russross/blackfriday/v2" in any of:
	/usr/lib/golang/src/github.com/russross/blackfriday/v2 (from $GOROOT)
	/home/yala/go/src/github.com/russross/blackfriday/v2 (from $GOPATH)
```

This is interesting, as the project is here at https://github.com/russross/blackfriday/ and it also has [a tag](https://github.com/russross/blackfriday/tags) for v2.0.1 ref. https://github.com/cooper/quiki/blob/master/go.sum#L72

Also

    go get github.com/russross/blackfriday/v2

does not work. Its readme states to install it with

    go get -u gopkg.in/russross/blackfriday.v2

Doing that also does not help to satisfy the dependency. Its readme also suggests to use dep or Glide for semantic versioning and package management.

**Comment by cooper** [comment]
I've noticed also it does not work when running in GOPATH mode with the blackfriday v2 dependency. I believe it should work if you clone the repository and build it outside of GOPATH. Can you confirm?

**Comment by cooper** [comment]
I think there's just something about the versioning in blackfriday that it does not like.

see:
https://github.com/russross/blackfriday/issues/565
https://github.com/russross/blackfriday/issues/587
