### ISSUE TITLE
utf-8 not properly supported

### ISSUE THREAD

**Issue by iefbr14** [cooper/quiki#95]
Set my wiki's name in the config file to:

@name: 日本 Wiki;

Note the Japanese 日本 characters. Perfectly valid utf-8

I also added text to the main.page using the same valid utf-8

I get consistent crap of: æ¥æ¬ 

This tells me the code is not treating input as utf-8 but as some other code page.

**Comment by cooper** [comment]
Fixed in 0.2.0. Thanks for bringing to my attention.
